#! /bin/bash
# Activation script

if [[ $PIXI_ENVIRONMENT_PLATFORMS == *"linux"* ]];
then
  # Conda compiler is named x86_64-conda-linux-gnu-c++, ccache can't resolve it
  # (https://ccache.dev/manual/latest.html#config_compiler_type)
  export CCACHE_COMPILERTYPE=gcc
fi

# Without -isystem, some LSP can't find headers
export PINOCCHIO_CXX_FLAGS="$PINOCCHIO_CXX_FLAGS -isystem $CONDA_PREFIX/include"

# Set default build value only if not previously set
export PINOCCHIO_BUILD_TYPE=${PINOCCHIO_BUILD_TYPE:=Release}
export PINOCCHIO_PYTHON_STUBS=${PINOCCHIO_PYTHON_STUBS:=ON}
export PINOCCHIO_COLLISION_SUPPORT=${PINOCCHIO_COLLISION_SUPPORT:=OFF}
export PINOCCHIO_ACCELERATE_SUPPORT=${PINOCCHIO_ACCELERATE_SUPPORT:=OFF}
export PINOCCHIO_CASADI_SUPPORT=${PINOCCHIO_CASADI_SUPPORT:=OFF}
export PINOCCHIO_AUTODIFF_SUPPORT=${PINOCCHIO_AUTODIFF_SUPPORT:=OFF}
export PINOCCHIO_EXTRA_SUPPORT=${PINOCCHIO_EXTRA_SUPPORT:=OFF}
export PINOCCHIO_OPENMP_SUPPORT=${PINOCCHIO_OPENMP_SUPPORT:=OFF}
export PINOCCHIO_CODEGEN_SUPPORT=${PINOCCHIO_CODEGEN_SUPPORT:=OFF}
export PINOCCHIO_SDF_SUPPORT=${PINOCCHIO_SDF_SUPPORT:=OFF}
export PINOCCHIO_MPFR_SUPPORT=${PINOCCHIO_MPFR_SUPPORT:=OFF}
export PINOCCHIO_FLOAT32_SUPPORT=${PINOCCHIO_FLOAT32_SUPPORT:=OFF}
export PINOCCHIO_BUILD_BENCHMARK=${PINOCCHIO_BUILD_BENCHMARK:=OFF}
