name: 🐞 Bug report
description: Something in Pinocchio is not working the way it should
title: "[Bug]: bug title"
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Follow the [contributing guidelines](../../development/contributing.md).

        If you have a question about how to use Pinocchio, open a [discussion](https://github.com/stack-of-tasks/pinocchio/discussions).

  - type: textarea
    id: description
    attributes:
      label: 🐞 Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction steps
      description: |
        Steps to reproduce the behavior. Provide a minimal example that reproduces the bug
        and a Dockerfile if it's an installation issue. Error messages and stack traces are also helpful.
        Use [Markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for code and stack traces.
      value: |
        ```python
        import pinocchio as pin
        ```

  - type: textarea
    id: traceback
    attributes:
      label: Relevant log output / Error message
      description: Copy and paste any relevant log output or error message.
      placeholder: Segmentation fault...
      render: shell

  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: |
        Describe the characteristics of your environment:
         * OS
         * Package manager used
         * Pinocchio version or SHA1 if built from source
         * All dependency versions
         * Compiler
         * CMake arguments
         * CMake output

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have checked that all my packages are installed from the same package manager (conda-forge, Nix, PyPI, robotpkg, ROS, ...)
          required: true
        - label: I have checked that there is no similar [issue](https://github.com/stack-of-tasks/pinocchio/issues)/[discussion](https://github.com/stack-of-tasks/pinocchio/discussions)
            in the repo
          required: true
        - label: I have provided a minimal and working example to reproduce the bug
          required: true
        - label: I have used [Markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for code, stack traces
            and compiler errors
          required: true
        - label: I have used an AI assistant
