pinocchio: Model Struct Reference
Model Struct Reference
Public Types
typedef se3::JointIndex JointIndex
typedef se3::GeomIndex GeomIndex
typedef se3::FrameIndex FrameIndex
typedef std::vector< Index > IndexVector
Public Member Functions
Model ()
Default constructor. Builds an empty model with no joints.
template<typename JointModelDerived >
JointIndex addJoint (const JointIndex parent, const JointModelBase< JointModelDerived > &joint_model, const SE3 &joint_placement, const std::string &joint_name, const Eigen::VectorXd &max_effort, const Eigen::VectorXd &max_velocity, const Eigen::VectorXd &min_config, const Eigen::VectorXd &max_config)
Add a joint to the kinematic tree with given bounds.
template<typename JointModelDerived >
JointIndex addJoint (const JointIndex parent, const JointModelBase< JointModelDerived > &joint_model, const SE3 &joint_placement, const std::string &joint_name)
Add a joint to the kinematic tree with infinite bounds.
int addJointFrame (const JointIndex &jointIndex, int frameIndex=-1)
Add a joint to the frame tree.
void appendBodyToJoint (const JointIndex joint_index, const Inertia &Y, const SE3 &body_placement=SE3::Identity())
Append a body to a given joint of the kinematic tree.
int addBodyFrame (const std::string &body_name, const JointIndex &parentJoint, const SE3 &body_placement=SE3::Identity(), int previousFrame=-1)
Add a body to the frame tree.
JointIndex getBodyId (const std::string &name) const
Return the index of a body given by its name.
bool existBodyName (const std::string &name) const
Check if a body given by its name exists.
JointIndex getJointId (const std::string &name) const
Return the index of a joint given by its name.
bool existJointName (const std::string &name) const
Check if a joint given by its name exists.
PINOCCHIO_DEPRECATED const std::string & getJointName (const JointIndex index) const
Get the name of a joint given by its index.
FrameIndex getFrameId (const std::string &name, const FrameType &type=(FrameType)(JOINT|FIXED_JOINT|BODY|OP_FRAME|SENSOR)) const
Returns the index of a frame given by its name.
bool existFrame (const std::string &name, const FrameType &type=(FrameType)(JOINT|FIXED_JOINT|BODY|OP_FRAME|SENSOR)) const
Checks if a frame given by its name exists.
int addFrame (const Frame &frame)
Adds a frame to the kinematic tree.
template<typename D >
bool check (const AlgorithmCheckerBase< D > &checker=AlgorithmCheckerBase< D >()) const
template<class T1 , class T2 , class T3 , class T4 , class T5 , class T6 , class T7 , class T8 , class T9 , class T10 >
bool check (const boost::fusion::list< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10 > &checkerList) const
bool check () const
Run check(fusion::list) with DEFAULT_CHECKERS as argument.
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef se3::Index Index
int nq
Dimension of the configuration vector representation.
int nv
Dimension of the velocity vector space.
int njoints
Number of joints.
int nbodies
Number of bodies.
int nframes
Number of operational frames.
container::aligned_vector< Inertia > inertias
Spatial inertias of the body expressed in the supporting joint frame .
container::aligned_vector< SE3 > jointPlacements
Placement (SE3) of the input of joint regarding to the parent joint output .
JointModelVector joints
Model of joint , encapsulated in a JointModelAccessor.
std::vector< JointIndex > parents
Joint parent of joint , denoted (li==parents[i]).
std::vector< std::string > names
Name of joint
Eigen::VectorXd neutralConfiguration
Vector of joint's neutral configurations.
Eigen::VectorXd effortLimit
Vector of maximal joint torques.
Eigen::VectorXd velocityLimit
Vector of maximal joint velocities.
Eigen::VectorXd lowerPositionLimit
Lower joint configuration limit.
Eigen::VectorXd upperPositionLimit
Upper joint configuration limit.
container::aligned_vector< Frame > frames
Vector of operational frames registered on the model.
std::vector< IndexVector > subtrees
Vector of subtrees. subtree[j] corresponds to the subtree supported by the joint j. The first element of subtree[j] is the index of the joint j itself.
Motion gravity
Spatial gravity of the model.
Static Public Attributes
static const Eigen::Vector3d gravity981
Default 3D gravity vector (=(0,0,-9.81)).
Protected Member Functions
void addJointIndexToParentSubtrees (const JointIndex joint_id)
Add the joint_id to its parent subtrees.
Detailed Description
Definition at line 39 of file model.hpp.
Member Function Documentation
int addBodyFrame (const std::string & body_name, const JointIndex & parentJoint, const SE3 & body_placement = SE3::Identity(), int previousFrame = -1) inline
Add a body to the frame tree.
Parameters
[in] body_name Name of the body.
[in] parentJoint Index of the parent joint.
[in] body_placement The relative placement of the body regarding to the parent joint. Set default to the Identity placement.
[in] previousFrame Index of the parent frame. If negative, the parent frame is the frame of the parent joint.
Returns
The index of the new frame or -1 in case of error.
Definition at line 145 of file model.hxx.
References Model::addFrame(), Model::frames, Model::getFrameId(), and Model::names.
int addFrame (const Frame & frame) inline
Adds a frame to the kinematic tree.
Parameters
[in] frame The frame to add to the kinematic tree.
Returns
Returns the index of the frame if it has been successfully added, -1 otherwise.
Definition at line 208 of file model.hxx.
References Model::existFrame(), Model::frames, FrameTpl< _Scalar, _Options >::name, Model::nframes, and FrameTpl< _Scalar, _Options >::type.
Referenced by Model::addBodyFrame(), Model::addJointFrame(), and Model::Model().
Model::JointIndex addJoint (const JointIndex parent, const JointModelBase< JointModelDerived > & joint_model, const SE3 & joint_placement, const std::string & joint_name, const Eigen::VectorXd & max_effort, const Eigen::VectorXd & max_velocity, const Eigen::VectorXd & min_config, const Eigen::VectorXd & max_config)
Add a joint to the kinematic tree with given bounds.
Remarks
This method does not add a Frame of same name to the vector of frames. Use Model::addJointFrame.
The inertia supported by the joint is set to Zero.
Template Parameters
JointModelDerived The type of the joint model.
Parameters
[in] parent Index of the parent joint.
[in] joint_model The joint model.
[in] joint_placement Placement of the joint inside its parent joint.
[in] joint_name Name of the joint. If empty, the name is random.
[in] max_effort Maximal joint torque.
[in] max_velocity Maximal joint velocity.
[in] min_config Lower joint configuration.
[in] max_config Upper joint configuration.
Returns
The index of the new joint.
See also
Model::appendBodyToJoint, Model::addJointFrame
Definition at line 56 of file model.hxx.
References Model::addJointIndexToParentSubtrees(), Model::effortLimit, Model::inertias, Model::jointPlacements, Model::joints, Model::lowerPositionLimit, Model::names, Model::neutralConfiguration, JointModelBase< Derived >::neutralConfiguration(), Model::njoints, Model::nq, Model::nv, Model::parents, Model::subtrees, Model::upperPositionLimit, and Model::velocityLimit.
Referenced by Model::addJoint().
Model::JointIndex addJoint (const JointIndex parent, const JointModelBase< JointModelDerived > & joint_model, const SE3 & joint_placement, const std::string & joint_name)
Add a joint to the kinematic tree with infinite bounds.
Remarks
This method also adds a Frame of same name to the vector of frames.
The inertia supported by the joint is set to Zero.
Template Parameters
JointModelDerived The type of the joint model.
Parameters
[in] parent Index of the parent joint.
[in] joint_model The joint model.
[in] joint_placement Placement of the joint inside its parent joint.
[in] joint_name Name of the joint. If empty, the name is random.
Returns
The index of the new joint.
See also
Model::appendBodyToJoint
Definition at line 106 of file model.hxx.
References Model::addJoint().
int addJointFrame (const JointIndex & jointIndex, int frameIndex = -1) inline
Add a joint to the frame tree.
Parameters
[in] jointIndex Index of the joint.
[in] frameIndex Index of the parent frame. If negative, the parent frame is the frame of the parent joint.
Returns
The index of the new frame or -1 in case of error.
Definition at line 122 of file model.hxx.
References Model::addFrame(), Model::frames, Model::getFrameId(), Model::names, and Model::parents.
void addJointIndexToParentSubtrees (const JointIndex joint_id) inline protected
Add the joint_id to its parent subtrees.
Parameters
[in] joint_id The id of the joint to add to the subtrees
Definition at line 222 of file model.hxx.
References Model::parents, and Model::subtrees.
Referenced by Model::addJoint().
void appendBodyToJoint (const JointIndex joint_index, const Inertia & Y, const SE3 & body_placement = SE3::Identity()) inline
Append a body to a given joint of the kinematic tree.
Parameters
[in] joint_index Index of the supporting joint.
[in] Y Spatial inertia of the body.
[in] body_placement The relative placement of the body regarding to the parent joint. Set default to the Identity placement.
See also
Model::addJoint
Definition at line 136 of file model.hxx.
References Model::inertias, Model::nbodies, and InertiaBase< Derived >::se3Action().
bool check (const AlgorithmCheckerBase< D > & checker = AlgorithmCheckerBase<D>()) const inline
Check the validity of the attributes of Model with respect to the specification of some algorithms.
The method is a template so that the checkers can be defined in each algorithms.
Parameters
[in] checker a class, typically defined in the algorithm module, that validates the attributes of model.
Returns
true if the Model is valid, false otherwise.
Definition at line 322 of file model.hpp.
bool check (const boost::fusion::list< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10 > & checkerList) const inline
Multiple checks for a fusion::vector of AlgorithmCheckerBase.
Run the check test for several conditons.
Parameters
[in] v fusion::vector of algo checkers. The param is typically initialize with boost::fusion::make_list(AlgoChecker1(), AlgoChecker2(), ...) make_list is defined in #include <boost/fusion/include/make_list.hpp>
Warning
no more than 10 checkers can be added (or Model API should be extended).
Note
This method is implemented in src/algo/check.hxx.
Definition at line 47 of file check.hxx.
bool existBodyName (const std::string & name) const inline
Check if a body given by its name exists.
Parameters
[in] name Name of the body.
Returns
True if the body exists in the kinematic tree.
Definition at line 164 of file model.hxx.
References Model::existFrame().
bool existFrame (const std::string & name, const FrameType & type = (FrameType) (JOINT | FIXED_JOINT | BODY | OP_FRAME | SENSOR)) const inline
Checks if a frame given by its name exists.
Parameters
[in] name Name of the frame.
[in] type Type of the frame.
Returns
Returns true if the frame exists.
Definition at line 201 of file model.hxx.
References Model::frames.
Referenced by Model::addFrame(), and Model::existBodyName().
bool existJointName (const std::string & name) const inline
Check if a joint given by its name exists.
Parameters
[in] name Name of the joint.
Returns
True if the joint exists in the kinematic tree.
Definition at line 178 of file model.hxx.
References Model::names.
Model::JointIndex getBodyId (const std::string & name) const inline
Return the index of a body given by its name.
Warning
If no body is found, return the number of elements at time T. This can lead to errors if the model is expanded after this method is called (for example to get the id of a parent body)
Parameters
[in] name Name of the body.
Returns
Index of the body.
Definition at line 159 of file model.hxx.
References Model::getFrameId().
Model::FrameIndex getFrameId (const std::string & name, const FrameType & type = (FrameType) (JOINT | FIXED_JOINT | BODY | OP_FRAME | SENSOR)) const inline
Returns the index of a frame given by its name.
See also
Model::existFrame to check if the frame exists or not.
Warning
If no frame is found, returns the size of the vector of Model::frames. This can lead to errors if the model is expanded after this method is called (for example to get the id of a parent frame).
Parameters
[in] name Name of the frame.
[in] type Type of the frame.
Returns
Index of the frame.
Definition at line 189 of file model.hxx.
References Model::frames.
Referenced by Model::addBodyFrame(), Model::addJointFrame(), and Model::getBodyId().
Model::JointIndex getJointId (const std::string & name) const inline
Return the index of a joint given by its name.
Warning
If no joint is found, return the number of elements at time T. This can lead to errors if the model is expanded after this method is called (for example to get the id of a parent joint)
Parameters
[in] index Index of the joint.
Returns
Index of the joint.
Definition at line 170 of file model.hxx.
References Model::names.
const std::string & getJointName (const JointIndex index) const inline
Get the name of a joint given by its index.
Parameters
[in] index Index of the joint.
Returns
Name of the joint.
Definition at line 183 of file model.hxx.
References Model::joints, and Model::names.
The documentation for this struct was generated from the following files:
model.hpp
check.hxx
default-check.hpp
multibody/model.cpp
model.hxx