name: Verify Pull Request Labels

on:
  pull_request_target:
    types: [opened, reopened, labeled, unlabeled]

jobs:
  verify_pr_labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify Pull Request Labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./.github/workflows/scripts/check_label.js');
            await script({github, context, core})
